#!/bin/sh
# Writes the Hugo module mounts for a set of versions.
#
#   gen-mounts.sh OUT VERSION=ROOT [VERSION=ROOT ...]    (OUT relative to SITE_DIR)
#
# Each ROOT holds <repo>/docs/site for the six source repos (a normal build
# passes v1.0=/src). The site-owned content/ is mounted once, for every
# version; each repo's docs/site/ is mounted at content/docs for its own
# version. Version names are listed exactly: in a version glob, * does not
# cross ".". There is no file filter and no index.md remap: the source lint
# has already rejected every form Hugo would misread.
set -eu
SITE_DIR=${SITE_DIR:-$(cd "$(dirname "$0")/.." && pwd)}
REPOS="opm core catalog_opm cli library opm-operator"
cd "$SITE_DIR"
out=$1; shift

names=""
for pair in "$@"; do names="$names${names:+, }\"${pair%%=*}\""; done

mkdir -p "$(dirname "$out")"
{
  echo '# Generated by scripts/gen-mounts.sh from OPM_VERSIONS. Do not edit.'
  for d in layouts assets static data i18n archetypes; do
    [ -d "$d" ] || continue
    printf '[[mounts]]\n  source = "%s"\n  target = "%s"\n' "$d" "$d"
  done
  printf '[[mounts]]\n  source = "content"\n  target = "content"\n  [mounts.sites.matrix]\n    versions = [%s]\n' "$names"
  for pair in "$@"; do
    v=${pair%%=*}; root=${pair#*=}
    for r in $REPOS; do
      [ -d "$root/$r/docs/site" ] || { echo "gen-mounts: $root/$r/docs/site is missing (version $v)" >&2; exit 1; }
      printf '[[mounts]]\n  source = "%s/%s/docs/site"\n  target = "content/docs"\n  [mounts.sites.matrix]\n    versions = ["%s"]\n' "$root" "$r" "$v"
    done
  done
} > "$out"
echo "gen-mounts: wrote $out ($(grep -c '^\[\[mounts\]\]' "$out") mounts, versions $names)"
