#!/bin/sh
# Writes the Hugo module mounts and the versions config for a set of versions.
#
#   gen-mounts.sh OUT VERSION=ROOT [VERSION=ROOT ...]    (OUT relative to SITE_DIR)
#
# Each ROOT holds <repo>/docs/site for the six source repos (a source = main
# version passes /src, an anchored or a line one its archive in
# .versions/<version>).
# The site-owned content/ is mounted once, for every version; each repo's
# docs/site/ is mounted at content/docs for its own version. Version names are
# listed exactly: in a version glob, * does not cross ".". There is no file
# filter and no index.md remap: the source lint has already rejected every
# form Hugo would misread. A version's generated reference, when
# SITE_DIR/.gen/<version>/ exists, is mounted at content for that version (its
# tree starts at docs/reference/...).
#
# Beside OUT (config/<env>/module.toml) it writes config/<env>/hugo.toml: the
# default version, each version's weight and its label (params.opm.versions,
# in weight order). They come from .versions/versions.tsv (site/versions.conf,
# resolved on the host) unless OPM_VERSIONS is set; then, and with no
# versions.tsv, the label is the name, the weight the position, and the first
# version is the default.
set -eu
SITE_DIR=${SITE_DIR:-$(cd "$(dirname "$0")/.." && pwd)}
REPOS="opm core catalog_opm cli library opm-operator"
cd "$SITE_DIR"
out=$1; shift

names=""
for pair in "$@"; do names="$names${names:+, }\"${pair%%=*}\""; done

mkdir -p "$(dirname "$out")"
{
  echo '# Generated by scripts/gen-mounts.sh from the version list. Do not edit.'
  for d in layouts assets static data i18n archetypes; do
    [ -d "$d" ] || continue
    printf '[[mounts]]\n  source = "%s"\n  target = "%s"\n' "$d" "$d"
  done
  printf '[[mounts]]\n  source = "content"\n  target = "content"\n  [mounts.sites.matrix]\n    versions = [%s]\n' "$names"
  for pair in "$@"; do
    v=${pair%%=*}; root=${pair#*=}
    if [ -d ".gen/$v" ]; then
      printf '[[mounts]]\n  source = ".gen/%s"\n  target = "content"\n  [mounts.sites.matrix]\n    versions = ["%s"]\n' "$v" "$v"
    fi
    for r in $REPOS; do
      [ -d "$root/$r/docs/site" ] || { echo "gen-mounts: $root/$r/docs/site is missing (version $v)" >&2; exit 1; }
      printf '[[mounts]]\n  source = "%s/%s/docs/site"\n  target = "content/docs"\n  [mounts.sites.matrix]\n    versions = ["%s"]\n' "$root" "$r" "$v"
    done
  done
} > "$out"
echo "gen-mounts: wrote $out ($(grep -c '^\[\[mounts\]\]' "$out") mounts, versions $names)"

# The versions config: "<name>\t<label>\t<weight>\t<default>" per version.
if [ -z "${OPM_VERSIONS:-}" ] && [ -f .versions/versions.tsv ]; then
  list=$(for pair in "$@"; do
    awk -F'\t' -v v="${pair%%=*}" '!/^#/ && $1 == v { print $1 "\t" $2 "\t" $3 "\t" $4; exit }' .versions/versions.tsv
  done)
else
  list=$(n=0; for pair in "$@"; do n=$((n + 1)); v=${pair%%=*}; printf '%s\t%s\t%s\t%s\n' "$v" "$v" "$n" "$([ $n = 1 ] && echo true || echo false)"; done)
fi
cfg=$(dirname "$out")/hugo.toml
printf '%s\n' "$list" | awk -F'\t' -v Q="'" '
  NF == 4 { n++; name[n] = $1; label[n] = $2; weight[n] = $3; if ($4 == "true") def = $1 }
  END {
    if (n == 0 || def == "") { print "gen-mounts: no versions, or no default version" > "/dev/stderr"; exit 1 }
    print "# Generated by scripts/gen-mounts.sh from the version list. Do not edit."
    printf "defaultContentVersion = " Q "%s" Q "\n[versions]\n", def
    for (i = 1; i <= n; i++) printf "  [versions." Q "%s" Q "]\n    weight = %s\n", name[i], weight[i]
    for (i = 1; i <= n; i++) printf "[[params.opm.versions]]\n  name = " Q "%s" Q "\n  label = " Q "%s" Q "\n", name[i], label[i]
  }' > "$cfg"
echo "gen-mounts: wrote $cfg (default $(sed -n "s/^defaultContentVersion = '\(.*\)'$/\1/p" "$cfg"))"
